---
title: Copula Resources
author: Davis Vaughan
date: '2018-03-06'
---

A number of resources I found useful while learning about copulas.

[NC State University lecture notes](https://www.stat.ncsu.edu/people/bloomfield/courses/st810j/slides/copula.pdf) - A consise introduction into copulas.
This is a good place to start but not a good place to find examples.

[Copulas for Finance: A Reading Guide and Some Applications](http://www.thierry-roncalli.com/download/copula-survey.pdf) - A much more intense survey of copulas.
Math heavy but full of examples.
Page 20 includes a few simulation techniques, but overcomplicates the simple ones (Gaussian copula) in order to stay general.

[Wiki: Copulas](https://en.wikipedia.org/wiki/Copula_(probability_theory)) - The mathematical definition section, along with Sklar's theorem and the section of Gaussian Copulas makes this worthwhile to look at.

[StackExchange answer](https://stats.stackexchange.com/questions/114786/in-definition-of-gaussian-copula-does-the-marginals-also-have-to-be-gaussian) - This was the missing link for me.
A great description of the "point of a copula." The full explanation in the last paragraph of the answer made things click for me.

[DataScience+](https://datascienceplus.com/modelling-dependence-with-copulas/) - A good walkthrough of using the `copula` R package.
Includes an example of using a t-copula with normal marginals.

[copula](https://cran.r-project.org/web/packages/copula/) - The copula R package.
A one stop shop for your copula needs if you use R and don't want to (or have to) implement it all yourself.

[Matlab example](https://www.mathworks.com/help/stats/examples/simulating-dependent-random-variables-using-copulas.html#d119e194) - Obviously the code is all in matlab, but they do a nice job of explaining how to simulate from copulas, without the theory.
